-- ================================================================
-- identity_columns_demo.sql
-- Demo: Exploring Oracle Identity Columns
-- ================================================================

-- Case 1: Basic identity column
CREATE TABLE temp (
    ID NUMBER GENERATED AS IDENTITY,
    text VARCHAR2(100)
);
DROP TABLE temp;

-- Case 2: Always as identity
CREATE TABLE temp (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    text VARCHAR2(100)
);
DROP TABLE temp;

-- Case 3: By default as identity
CREATE TABLE temp (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR2(100)
);
DROP TABLE temp;

-- Case 4: By default on null as identity
CREATE TABLE temp (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    text VARCHAR2(100)
);
DROP TABLE temp;

-- Case 5: Identity with custom START and INCREMENT
CREATE TABLE temp (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
       START WITH 50 INCREMENT BY 3,
    text VARCHAR2(100)
);

-- Insert examples
INSERT INTO temp (ID, text) VALUES (1, 'Test with 1');
INSERT INTO temp (ID, text) VALUES (20, 'Test with 20');
INSERT INTO temp (ID, text) VALUES (NULL, 'Test with NULL');
INSERT INTO temp (text) VALUES ('Test with No Value');

-- View results
SELECT * FROM temp;

-- Inspect the hidden sequence Oracle creates internally
-- Replace the sequence name with the one from your database
SELECT * FROM user_objects WHERE object_name = 'ISEQ$$_74510';
SELECT * FROM user_sequences WHERE sequence_name = 'ISEQ$$_74510';
SELECT ISEQ$$_74510.NEXTVAL FROM dual;

-- Cleanup
DROP TABLE temp;
PURGE RECYCLEBIN;
