-- ============================================================================
-- File: schema.sql
-- Author: Senbanjo Hector Ademola
-- Created: 2025-08-01
-- Purpose: Define core schema for Oracle Autonomous Database demo (departments + employees)
-- Example usage: Run in SQL Developer Web to create tables and insert sample data
-- Notes: Referential integrity enforced via foreign key
-- ============================================================================

CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL
);

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    hire_date DATE DEFAULT SYSDATE,
    salary NUMBER(10,2),
    department_id NUMBER,
    CONSTRAINT fk_dept FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
);

-- Sample data
INSERT INTO departments (department_name) VALUES ('Finance');
INSERT INTO departments (department_name) VALUES ('Engineering');
INSERT INTO departments (department_name) VALUES ('Human Resources');

INSERT INTO employees (first_name, last_name, email, salary, department_id)
VALUES ('Ada', 'Okoro', 'ada.okoro@example.com', 55000, 2);

INSERT INTO employees (first_name, last_name, email, salary, department_id)
VALUES ('Tunde', 'Adebayo', 'tunde.adebayo@example.com', 48000, 1);

COMMIT;
